on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

name: Release Please

env:
  NODE_ENV: production

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build && bun run docs

      - name: Run tests
        run: bun test

  release-please:
    name: Execute release chores

    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    needs: build-test

    outputs:
      created: ${{ steps.release.outputs.release_created }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

  # publish:
  #   name: Publish to npm

  #   runs-on: ubuntu-latest
  #   needs: release-please
  #   if: ${{ needs.release-please.outputs.created == 'true' }}

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Bun
  #       uses: oven-sh/setup-bun@v2

  #     - name: Install dependencies
  #       run: bun install

  #     - name: Publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       run: bun publish
